name: cachepot
version: '0.1.0'
version-script: |
    git describe --tags

summary: cachepot is a fork of sccache and also ccache with cloud storage and security
description: |
    cachepot is a ccache-like tool. It is used as a compiler wrapper and avoids
    compilation when possible, storing a cache in a remote storage using the
    Amazon Simple Cloud Storage Service (S3) API, the Google Cloud Storage (GCS)
    API, or Redis.

grade: stable
confinement: classic

apps:
    sccache:
        command: bin/cachepot.wrapper

    cachepot-server:
        environment:
            SCCACHE_START_SERVER: 1
            SCCACHE_NO_DAEMON: 1
            SCCACHE_IDLE_TIMEOUT: 0
        command: bin/cachepot.wrapper
        daemon: simple

parts:
    cachepot:
        plugin: rust
        source: .
        source-type: git
        build-packages:
        - libssl-dev
        - make
        - pkg-config
        rust-features:
        - gcs
        - redis
        - s3

    wrapper:
        plugin: dump
        source: snap
        prime: [bin]
